export interface SamplePoint {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  date: string;
  riskLevel: "Low" | "Medium" | "High" | "Critical";
  bacterialCount: number;
  pH: number;
  temperature: number;
  turbidity: number;
  dissolvedOxygen: number;
  sampleType: "Water" | "Soil" | "Sediment";
  argsDetected: string[];
}

export const SAMPLE_POINTS: SamplePoint[] = [
  {
    id: "RC-001",
    name: "Rapid Creek - Canyon Lake Park",
    latitude: 44.0825,
    longitude: -103.2650,
    date: "2026-01-15",
    riskLevel: "Low",
    bacterialCount: 45,
    pH: 7.3,
    temperature: 4.2,
    turbidity: 3.1,
    dissolvedOxygen: 10.2,
    sampleType: "Water",
    argsDetected: [],
  },
  {
    id: "RC-002",
    name: "Rapid Creek - Downtown Bridge",
    latitude: 44.0805,
    longitude: -103.2310,
    date: "2026-01-15",
    riskLevel: "Medium",
    bacterialCount: 320,
    pH: 6.9,
    temperature: 5.1,
    turbidity: 12.5,
    dissolvedOxygen: 7.8,
    sampleType: "Water",
    argsDetected: ["intI1", "sul1"],
  },
  {
    id: "RC-003",
    name: "Storybook Island Park Pond",
    latitude: 44.0780,
    longitude: -103.2570,
    date: "2026-01-28",
    riskLevel: "Medium",
    bacterialCount: 210,
    pH: 7.1,
    temperature: 3.8,
    turbidity: 8.3,
    dissolvedOxygen: 8.5,
    sampleType: "Water",
    argsDetected: ["tetW"],
  },
  {
    id: "RC-004",
    name: "Memorial Park Drainage",
    latitude: 44.0845,
    longitude: -103.2245,
    date: "2026-01-28",
    riskLevel: "High",
    bacterialCount: 1850,
    pH: 6.5,
    temperature: 6.2,
    turbidity: 28.4,
    dissolvedOxygen: 5.3,
    sampleType: "Water",
    argsDetected: ["intI1", "sul1", "tetW", "blaTEM"],
  },
  {
    id: "RC-005",
    name: "Founder's Park Creek",
    latitude: 44.0770,
    longitude: -103.2180,
    date: "2026-02-10",
    riskLevel: "Low",
    bacterialCount: 65,
    pH: 7.4,
    temperature: 2.5,
    turbidity: 2.8,
    dissolvedOxygen: 11.0,
    sampleType: "Water",
    argsDetected: [],
  },
  {
    id: "RC-006",
    name: "Sioux Park Soil Sample",
    latitude: 44.0720,
    longitude: -103.2400,
    date: "2026-02-10",
    riskLevel: "Medium",
    bacterialCount: 580,
    pH: 6.8,
    temperature: 1.2,
    turbidity: 15.0,
    dissolvedOxygen: 6.5,
    sampleType: "Soil",
    argsDetected: ["sul1", "tetW"],
  },
  {
    id: "RC-007",
    name: "Dark Canyon Creek",
    latitude: 44.0680,
    longitude: -103.2520,
    date: "2026-02-24",
    riskLevel: "High",
    bacterialCount: 2400,
    pH: 6.3,
    temperature: 8.5,
    turbidity: 35.2,
    dissolvedOxygen: 4.8,
    sampleType: "Water",
    argsDetected: ["intI1", "sul1", "blaTEM", "tetW", "mcr-1"],
  },
  {
    id: "RC-008",
    name: "Box Elder Creek Confluence",
    latitude: 44.1050,
    longitude: -103.1800,
    date: "2026-02-24",
    riskLevel: "Critical",
    bacterialCount: 5200,
    pH: 5.9,
    temperature: 10.3,
    turbidity: 52.0,
    dissolvedOxygen: 3.2,
    sampleType: "Water",
    argsDetected: ["intI1", "sul1", "tetW", "blaTEM", "vanA", "mcr-1", "blaKPC"],
  },
  {
    id: "RC-009",
    name: "Spring Creek South",
    latitude: 44.0550,
    longitude: -103.2100,
    date: "2026-03-05",
    riskLevel: "Low",
    bacterialCount: 35,
    pH: 7.5,
    temperature: 6.0,
    turbidity: 1.5,
    dissolvedOxygen: 11.5,
    sampleType: "Water",
    argsDetected: [],
  },
  {
    id: "RC-010",
    name: "Rushmore Mall Urban Runoff",
    latitude: 44.0920,
    longitude: -103.2050,
    date: "2026-03-05",
    riskLevel: "High",
    bacterialCount: 1500,
    pH: 6.6,
    temperature: 9.0,
    turbidity: 22.0,
    dissolvedOxygen: 5.5,
    sampleType: "Sediment",
    argsDetected: ["intI1", "sul1", "tetW", "blaKPC"],
  },
];
